#!/bin/sh
PERSONA_PATTERN="s|^persona\.\(.*\) \(.* .*\) <\(.*\)>$|"

function install () {
  TEMPLATE_DIR=~/.git/templates
  HOOK_TEMPLATE_DIR=$TEMPLATE_DIR/hooks
  HOOK_FILE=$HOOK_TEMPLATE_DIR/pre-commit
  COMMAND="git-persona check"
  LOCAL_HOOK_FILE="$(git rev-parse --show-toplevel)/.git/hooks/pre-commit"

  mkdir -p $HOOK_TEMPLATE_DIR

  if [ -e $HOOK_FILE ]; then
    grep -q "$COMMAND" $HOOK_FILE || echo $COMMAND >> $HOOK_FILE
  else
    echo "$COMMAND" >> $HOOK_FILE
    chmod +x $HOOK_FILE
  fi

  if [ -e $LOCAL_HOOK_FILE ]; then
    grep -q "$COMMAND" $LOCAL_HOOK_FILE || echo "$COMMAND" >> $LOCAL_HOOK_FILE
  fi
  git config --global init.templatedir $TEMPLATE_DIR
  git init
}

function list_persona () {
  USER_NAME=$(git config --local --get user.name)
  USER_EMAIL=$(git config --local --get user.email)
  PERSONA_LIST=$(git config --global --get-regex ^persona\\. | grep -e "^persona.*$")

  while read -r line; do
      PERSONA=$(sed -n "$PERSONA_PATTERN\\1|p" <<< $line)
      PERSONA_NAME=$(sed -n "$PERSONA_PATTERN\\2|p" <<< $line)
      PERSONA_EMAIL=$(sed -n "$PERSONA_PATTERN\\3|p" <<< $line)
      if [ "$USER_NAME" = "$PERSONA_NAME" ] && [ "$USER_EMAIL" =  "$PERSONA_EMAIL" ]; then
        USING='*'
      else
        USING=" "
      fi
     echo "\t $USING $PERSONA - NAME: $PERSONA_NAME EMAIL: <$PERSONA_EMAIL>"
  done <<< "$PERSONA_LIST"
}

function set_persona () {
  PERSONA=$(git config --global --get-regex ^persona\\. | grep -e "^persona.$1")

  if [ -n "$PERSONA" ]; then
    PERSONA_NAME=$(sed -n "$PERSONA_PATTERN\\2|p" <<< $PERSONA)
    PERSONA_EMAIL=$(sed -n "$PERSONA_PATTERN\\3|p" <<< $PERSONA)
    git config --local user.name "$PERSONA_NAME"
    git config --local user.email "$PERSONA_EMAIL"
  else
    echo "$1 is not a persona"
  fi

  list_persona
}

function check_username () {
  USER_NAME=$(git config --local --get user.name)
  USER_EMAIL=$(git config --local --get user.email)
  if [ -z "$USER_NAME" ] || [ -z "$USER_EMAIL" ]; then
    echo "It seems you're missing either user.name or user.email in your local config"
    echo "Select the persona name you would like to use for this repository: "
    exec < /dev/tty
    select persona in $(git config --global --get-regex ^persona\\. | grep -e "^persona.*$" | sed -n "$PERSONA_PATTERN\\1|p"); do
      set_persona $persona
      break
    done
  fi
}

if [ "$#" -eq 0 ]; then
  list_persona
  exit 0
elif [ "$#" -eq 1 ]; then
  if [ "$1" = "install" ]; then
    install
    exit 0
  elif [ "$1" = "check" ]; then
    check_username
    exit 0
  else
    set_persona $1
    exit 0
  fi
else
  echo "Too many arguments" #TODO
fi
