#!/bin/sh
PERSONA_PATTERN="s|^persona\.\(.*\) \(.* .*\) <\(.*\)>$|"

install () {
  TEMPLATE_DIR=~/.git/templates
  HOOK_TEMPLATE_DIR=$TEMPLATE_DIR/hooks
  HOOK_FILE=$HOOK_TEMPLATE_DIR/pre-commit
  COMMAND="git-persona check"
  LOCAL_HOOK_FILE="$(git rev-parse --show-toplevel)/.git/hooks/pre-commit"

  mkdir -p $HOOK_TEMPLATE_DIR

  if [ -e $HOOK_FILE ]; then
    grep -q "$COMMAND" $HOOK_FILE || echo $COMMAND >> $HOOK_FILE
  else
    echo "$COMMAND" >> $HOOK_FILE
    chmod +x $HOOK_FILE
  fi

  if [ -e $LOCAL_HOOK_FILE ]; then
    grep -q "$COMMAND" $LOCAL_HOOK_FILE || echo "$COMMAND" >> $LOCAL_HOOK_FILE
  fi
  git config --global init.templatedir $TEMPLATE_DIR
  git init
}

list_persona () {
  USER_NAME=$(git config --local --get user.name)
  USER_EMAIL=$(git config --local --get user.email)
  PERSONA_LIST=$(git config --global --get-regex ^persona\\. | grep -e "^persona.*$")

  NUMBER=1
  echo "$PERSONA_LIST" | while read -r line; do
      PERSONA=$(echo "$line" | sed -n "$PERSONA_PATTERN\\1|p")
      PERSONA_NAME=$(echo "$line" | sed -n "$PERSONA_PATTERN\\2|p")
      PERSONA_EMAIL=$(echo "$line" | sed -n "$PERSONA_PATTERN\\3|p")

      if [ "$USER_NAME" = "$PERSONA_NAME" ] && [ "$USER_EMAIL" = "$PERSONA_EMAIL" ]; then
        USING='*'
      else
        USING=''
      fi
      if [ "$#" -eq 1 ]; then
        NUMBERING="$NUMBER) "
      else
        NUMBERING=''
      fi
      printf ' %-4s%-1s %s - NAME: %s EMAIL: <%s>\n' "$NUMBERING" "$USING" "$PERSONA" "$PERSONA_NAME" "$PERSONA_EMAIL"
      NUMBER=`expr $NUMBER + 1`
  done
}

set_persona () {
  if [ -n "$1" ]; then
    PERSONA=$(git config --global --get-regex ^persona\\. | grep -e "^persona.$1")

    if [ -n "$PERSONA" ]; then
      PERSONA_NAME=$(echo "$PERSONA" | sed -n "$PERSONA_PATTERN\\2|p")
      PERSONA_EMAIL=$(echo "$PERSONA" | sed -n "$PERSONA_PATTERN\\3|p")
      git config --local user.name "$PERSONA_NAME"
      git config --local user.email "$PERSONA_EMAIL"
    else
      printf "%s is not a persona\n" "$1"
    fi
    list_persona
  fi
}

check_username () {
  USER_NAME=$(git config --local --get user.name)
  USER_EMAIL=$(git config --local --get user.email)

  if [ -z "$USER_NAME" ] || [ -z "$USER_EMAIL" ]; then
    PERSONAS=$(list_persona "number")
    printf "Select the persona you would like to use for this repository\n\n%s\n" "$PERSONAS"
    printf "> "
    exec < /dev/tty
    read SELECT
    PERSONA=$(echo "$PERSONAS" | sed -n "s|$SELECT)[ \*]*\([a-zA-Z]*\) .*$|\\1|p")
    set_persona $PERSONA
  fi
}

if [ "$#" -eq 0 ]; then
  list_persona
  exit 0
elif [ "$#" -eq 1 ]; then
  if [ "$1" = "install" ]; then
    install
    exit 0
  elif [ "$1" = "check" ]; then
    check_username
    exit 0
  else
    set_persona $1
    exit 0
  fi
else
  echo "Too many arguments" #TODO Better messeging
fi
